### PR TITLE
[2] Support for Windows 2008R2

### LINKED ISSUE #2: Windows 2008 (R2) support is spotty
Apparently there are issues with Windows 2008 (R2) displaying the full list of installed HotFixes. I'm not sure about the underlying cause, but here is [another way to detect the hotfix list](https://bogner.sh/2017/05/how-to-check-if-ms17-010-has-already-been-installed/).

### PR DESCRIPTION
**Pull request by rnelson0**
I was able to verify this works on my own 2008R2, 2012R2 servers and my Windows 7, 8.1 desktops.

Fixes #2

### CODE REVIEW

**Comment by ccaum** [comment]
@SeanTecha and @BillWeiss  Can you take a look? This looks good to me, but I don't know Windows :)

**Comment by SeanTecha** [comment]
@rnelson0 Hi Rob, thanks for the PR. When trying this out on my Windows Server 2012 R2 machine, I get this error:

Exception calling "QueryHistory" with "2" argument(s): "Exception from HRESULT: 0x80240007"
At line:14 char:1
  $all = $wu.QueryHistory(0,$totalupdates)
      CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
      FullyQualifiedErrorId : ComMethodTargetInvocation

Looking around, this might be because the machine has automatic updates turned off and that makes $totalupdates return 0. $wu.QueryHistory(0, 0) results in the same error. A simple check for $totalupdates' value before that command would probably do?

**Comment by rnelson0** [comment]
@SeanTecha Updated to guard against a 0 response.

**Comment by SeanTecha** [comment]
Thank you, works great @rnelson0!

**Pull request merged**
